<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="0" failures="1" finished="true" name="Test Run: 54" tests="1" total_time="Finished in: 0.00 secs."/>
<test location="/Users/nathanvaughn/Documents/GitHub/Greens-Functions-Iterative-Methods/cell-AMR/tests/testCell.py" status="fail" test="TestCell.testGradientPsi" time="">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "/Users/nathanvaughn/Documents/GitHub/Greens-Functions-Iterative-Methods/cell-AMR/tests/testCell.py", line 43, in testGradientPsi
    self.assertEqual(self.Cell.grad[2][1,0,0], 0, "z gradient not as expected along x axis")
AssertionError: -0.17423910890869904 != 0 : z gradient not as expected along x axis
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="cell-AMR testCell.py [pyunit run]"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
